#include "DrawDataConfig.h"

namespace graph {

std::map<int, DrawData> DrawDataConfig::configs_ = {
    {1, {
        .pngFile = "assets/png/01_graph.png",
        .txtFile = "assets/txt/01_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Сгенерированный граф",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {2, {
        .pngFile = "assets/png/02_adjacency_matrix.png",
        .txtFile = "assets/txt/02_adjacency_matrix.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица смежности",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {3, {
        .pngFile = "assets/png/03_weight_matrix.png",
        .txtFile = "assets/txt/03_weight_matrix.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица весов",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {12, {
        .pngFile = "assets/png/12_paths.png",
        .txtFile = "assets/txt/12_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "assets/txt/12_paths.txt",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Найденные пути",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {13, {
        .pngFile = "assets/png/13_shimbell_min.png",
        .txtFile = "assets/txt/13_shimbell_min.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица минимальных расстояний Шимбелла",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {14, {
        .pngFile = "assets/png/13_shimbell_max.png",
        .txtFile = "assets/txt/13_shimbell_max.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица максимальных расстояний Шимбелла",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {15, {
        .pngFile = "assets/png/15_graph_metrics.png",
        .txtFile = "assets/txt/15_graph.txt",
        .txtColorsFile = "assets/txt/15_metrics_colors.txt",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Метрики графа",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {21, {
        .pngFile = "",
        .txtFile = "assets/txt/21_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "assets/txt/21_bfs_edges.txt",
        .gifFile = "assets/gif/21_bfs.gif",
        .title = "BFS-анимация",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {22, {
        .pngFile = "assets/png/22_dijkstra.png",
        .txtFile = "assets/txt/22_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "assets/txt/22_dijkstra_path.txt",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Путь Дейкстры",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {23, {
        .pngFile = "assets/png/23_compare.png",
        .txtFile = "assets/txt/23_compare.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Сравнение алгоритмов",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {31, {
        .pngFile = "assets/png/31_flow_network.png",
        .txtFile = "assets/txt/31_flow.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Сеть потоков",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {32, {
        .pngFile = "assets/png/32_max_flow.png",
        .txtFile = "assets/txt/31_flow.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "assets/gif/32_flow_animation.gif",
        .title = "Максимальный поток",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {33, {
        .pngFile = "assets/png/33_min_cost_flow_path.png",
        .txtFile = "assets/txt/33_flow.txt",
        .txtColorsFile = "",
        .txtPathsFile = "assets/txt/33_path.txt",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Путь минимальной стоимости",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {34, {
        .pngFile = "assets/png/34_capacity_matrix.png",
        .txtFile = "assets/txt/34_capacity_matrix.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица пропускных способностей",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {35, {
        .pngFile = "assets/png/35_cost_matrix.png",
        .txtFile = "assets/txt/35_cost_matrix.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Матрица стоимостей",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {41, {
        .pngFile = "assets/png/41_spanning_tree.png",
        .txtFile = "assets/txt/41_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Минимальное остовное дерево (алгоритм Борувки)",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {42, {
        .pngFile = "assets/png/42_graph.png",
        .txtFile = "assets/txt/42_graph.txt",
        .txtColorsFile = "assets/txt/42_colors.txt",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Граф для кодирования",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {43, {
        .pngFile = "assets/png/43_graph.png",
        .txtFile = "assets/txt/43_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "assets/txt/43_added_edges.txt",
        .gifFile = "",
        .title = "Кодирование Прюфера",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {44, {
        .pngFile = "assets/png/44_graph.png",
        .txtFile = "assets/txt/44_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Декодирование Прюфера",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {45, {
        .pngFile = "assets/png/45_graph.png",
        .txtFile = "assets/txt/45_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Граф для проверки",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {46, {
        .pngFile = "assets/png/46_coloring.png",
        .txtFile = "assets/txt/46_graph.txt",
        .txtColorsFile = "assets/txt/46_colors.txt",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "Раскраска графа",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {51, {
        .pngFile = "assets/png/51_euler_cycle.png",
        .txtFile = "assets/txt/51_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "assets/txt/51_path.txt",
        .txtGraphFile = "assets/txt/51_added_edges.txt",
        .gifFile = "",
        .title = "Эйлеров цикл",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {52, {
        .pngFile = "assets/png/52_cuts.png",
        .txtFile = "assets/txt/52_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "assets/txt/52_selected_cut_edges.txt",
        .gifFile = "",
        .title = "Система разрезов",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {53, {
        .pngFile = "assets/png/53_tsp_cycle.png",
        .txtFile = "assets/txt/53_graph.txt",
        .txtColorsFile = "",
        .txtPathsFile = "assets/txt/53_path.txt",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "TSP-цикл",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {61, {
        .pngFile = "assets/png/61_hashtable_demo.png",
        .txtFile = "assets/txt/hashtable_demo.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "HashTable Demo",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {62, {
        .pngFile = "assets/png/62_rbtree_demo.png",
        .txtFile = "assets/txt/62_rbtree_demo.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "RBTree Demo",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {63, {
        .pngFile = "assets/png/63_hashtable_interactive.png",
        .txtFile = "assets/txt/63_hashtable_interactive.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "HashTable Interactive",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {64, {
        .pngFile = "assets/png/64_rbtree_interactive.png",
        .txtFile = "assets/txt/64_rbtree_interactive.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "",
        .title = "RBTree Interactive",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }},
    {65, {
        .pngFile = "",
        .txtFile = "assets/txt/65_rbtree_snapshots.txt",
        .txtColorsFile = "",
        .txtPathsFile = "",
        .txtGraphFile = "",
        .gifFile = "assets/gif/65_rbtree_growth.gif",
        .title = "RBTree Growth Animation",
        .colors = {},
        .path = {},
        .addedEdges = {},
        .paths = {}
    }}
};

const std::map<int, DrawData>& DrawDataConfig::getConfigs() {
    return configs_;
}

}  // namespace graph
