FIGSIZE = (12, 8)
SEED = 42
FONTSIZE = 10
TITLE_FONT_SIZE = 15
TITLE_FONT_WEIGHT = 'bold'

NODE_SIZE = 800
NODE_COLOR = 'skyblue'
NODE_EDGE_COLOR = 'black'
NODE_EDGE_WIDTH = 2.0
PATH_NODE_COLOR = 'orange'
FLOW_NODE_COLOR = 'lightblue'


ARROW_STYLE = '-|>'
ARROW_SIZE = 30
CONNECTION_STYLE = 'arc3,rad=0.1'
MIN_SOURCE_MARGIN = 15
MIN_TARGET_MARGIN = 15
DEFAULT_EDGE_COLOR = 'gray'
DEFAULT_EDGE_WIDTH = 1.5
DEFAULT_EDGE_ALPHA = 0.7
PATH_EDGE_COLOR = 'red'
PATH_EDGE_WIDTH = 4.5
PATH_EDGE_ALPHA = 0.9
FLOW_EDGE_ALPHA = 0.8

ADDED_EDGE_COLOR = '#C71585'
ADDED_EDGE_WIDTH = 5.0

LABEL_FONT_SIZE = 13
LABEL_FONT_WEIGHT = 'bold'
LABEL_FONT_COLOR = 'black'
EDGE_LABEL_FONT_SIZE = 10
EDGE_LABEL_FONT_COLOR = 'darkred'
EDGE_LABEL_FONT_WEIGHT = 'normal'
EDGE_LABEL_BBOX = dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='none', alpha=0.8)

GRAPH_COLORMAP = 'magma'
FLOW_COLORMAP = 'RdYlGn_r'

LEGEND_NODE_MARKER = 'o'
LEGEND_EDGE_STYLE = '-'
LEGEND_NODE_SIZE = 14

MATRIX_FIGSIZE = (10, 10)
MATRIX_COLORMAP = 'viridis'
MATRIX_TITLE_SIZE = 15
MATRIX_ANNOT_SIZE = 10
